language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t cellokrecik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cellokrecik/react-test npm test

after_success:
  - docker build -t cellokrecik/multi-client:latest ./client
  - docker build -t cellokrecik/multi-nginx:latest ./nginx
  - docker build -t cellokrecik/multi-server:latest ./server
  - docker build -t cellokrecik/multi-worker:latest ./worker
  - echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_ID)" docker.io --password-stdin    
  - docker push cellokrecik/multi-client:latest
  - docker push cellokrecik/multi-nginx:latest
  - docker push cellokrecik/multi-server:latest
  - docker push cellokrecik/multi-worker:latest


