language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t emiliatraczyk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emiliatraczyk/react-test npm test

after_success:
  - docker build -t emiliatraczyk/multi-client ./client
  - docker build -t emiliatraczyk/multi-nginx ./nginx
  - docker build -t emiliatraczyk/multi-server ./server
  - docker build -t emiliatraczyk/multi-worker ./worker
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_ID -p $DOCKER_PASSWORD;
      make push-image;
  - docker push emiliatraczyk/multi-client
  - docker push emiliatraczyk/multi-nginx
  - docker push emiliatraczyk/multi-server
  - docker push emiliatraczyk/multi-worker


